LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

FREETYPE_LIBRARY_PATH := external/freetype-2.4.12

LOCAL_MODULE := SDL2_ttf

LOCAL_C_INCLUDES := $(LOCAL_PATH)

LOCAL_SRC_FILES := $(TARGET_ARCH_ABI)/libSDL2_ttf.so

ifneq ($(FREETYPE_LIBRARY_PATH),)
    LOCAL_C_INCLUDES += $(LOCAL_PATH)/$(FREETYPE_LIBRARY_PATH)/include
endif

LOCAL_EXPORT_C_INCLUDES += $(LOCAL_C_INCLUDES)

include $(PREBUILT_SHARED_LIBRARY)
