/**
 * Generates allowed semantic PR title schema for project.
 *
 * 1. collects list of all mod IDs
 * 2. generate list of allowed scopes using mod IDs
 * 3. write to `.github/semantic.yaml` file
 * 4. write to `doc/src/assets/semantic.json` file
 */

import { walk } from "@std/fs"
import { asynciter } from "$asynciter/mod.ts"
import { SafeParseSuccess, z } from "$zod/mod.ts"
import * as YAML from "@std/yaml"
import { outdent } from "$outdent/mod.ts"
import { resolve } from "@std/path"

type Config = {
  enabled: boolean
  titleOnly: boolean
  commitsOnly: boolean
  titleAndCommits: boolean
  anyCommit: boolean
  scopes: readonly string[] | null
  types: readonly string[]
  allowMergeCommits: boolean
  allowRevertCommits: boolean
  targetUrl: string
}

const types = [
  "feat",
  "fix",
  "docs",
  "style",
  "refactor",
  "perf",
  "test",
  "build",
  "ci",
  "chore",
  "revert",
] as const

type Modinfo = z.infer<typeof modinfoSchema>

/** Extracts ID from Modinfo entry. */
export const modinfoSchema = z
  .object({ type: z.literal("MOD_INFO"), id: z.string() })
  .transform((x) => x.id)

const parseModinfos = (xs: unknown[]) => xs.map((x) => modinfoSchema.safeParse(x))

/**
 * @param path Path to `modinfo.json` file.
 * @returns Mod ID or `undefined` if file is invalid.
 */
export const extractModinfo = (path: string): Promise<string | undefined> =>
  Deno
    .readTextFile(path)
    .then(JSON.parse)
    .then(parseModinfos)
    .then((xs) => xs.find((x): x is SafeParseSuccess<Modinfo> => x.success)?.data)

/** List of all mod IDs. */
export const allModIds = await asynciter(walk("data/mods", {
  maxDepth: 2,
  includeDirs: false,
  exts: [".json"],
  match: [/modinfo\.json/],
  skip: [/bn/],
}))
  .map(({ path }) => path)
  .concurrentUnorderedMap(extractModinfo)
  .collect()
  .then((xs) => xs.filter((x) => x !== undefined))

/**
 * see `changelog_guidelines.md` for list of all allowed scopes.
 */
export const scopes = {
  /** Default allowed scopes */
  base: ["UI", "i18n", "balance", "port"],
  /** List of `mods/<MOD_ID>` */
  mods: allModIds.toSorted().map((x) => `mods/${x}`),
}

// https://github.com/Ezard/semantic-prs?tab=readme-ov-file#configuration
const config: Partial<Config> = {
  enabled: true,
  titleOnly: true,
  targetUrl: "https://docs.cataclysmbn.org/en/contribute/changelog_guidelines/",

  types,
  scopes: Object.values(scopes).flat(),
}

if (import.meta.main) {
  const setting = YAML.stringify(config)
  const content = outdent`
      # This file is generated by \`scripts/semantic.ts\`, do not edit manually.
      #
      # For more on configuration:
      # https://github.com/Ezard/semantic-prs?tab=readme-ov-file#configuration-options
      #
      # Validate the PR title, and ignore all commit messages
      ${setting}
    `

  const rootPath = resolve(import.meta.dirname!, "..")

  await Promise.all([
    Deno.writeTextFile(resolve(rootPath, ".github/semantic.yml"), content),
    Deno.writeTextFile(
      resolve(rootPath, "doc/src/assets/semantic.json"),
      JSON.stringify({ types: config.types, scopes: config.scopes }, null, 2) + "\n",
    ),
  ])
}
