#!/usr/bin/env -S deno run --allow-read=data/mods --allow-write=.github/semantic.yml
/**
 * Generates allowed semantic PR title schema for project.
 *
 * 1. collects list of all mod IDs
 * 2. generate list of allowed scopes using mod IDs
 * 3. write to `.github/semantic.yaml` file
 */

import { walk } from "@std/fs"
import { asynciter } from "$asynciter/mod.ts"
import * as YAML from "@std/yaml/unstable-stringify"
import { outdent } from "$outdent/mod.ts"
import { resolve } from "@std/path"
import * as v from "@valibot/valibot"

type Config = {
  enabled: boolean
  titleOnly: boolean
  commitsOnly: boolean
  titleAndCommits: boolean
  anyCommit: boolean
  scopes: readonly string[] | null
  types: readonly string[]
  allowMergeCommits: boolean
  allowRevertCommits: boolean
  targetUrl: string
}

const types = [
  "feat",
  "fix",
  "docs",
  "style",
  "refactor",
  "perf",
  "test",
  "build",
  "ci",
  "chore",
  "revert",
] as const

/** Extracts ID from Modinfo entry. */
export const modinfoSchema = v.pipe(
  v.object({ type: v.literal("MOD_INFO"), id: v.string() }),
  v.transform((x) => x.id),
)

const parseModinfos = (xs: unknown[]) =>
  xs.flatMap((x) => {
    const parsed = v.safeParse(modinfoSchema, x)
    return parsed.success ? [parsed.output] : []
  })

/**
 * @param path Path to `modinfo.json` file.
 * @returns Mod ID or `undefined` if file is invalid.
 */
export const extractModinfo = (path: string): Promise<string | undefined> =>
  Deno
    .readTextFile(path)
    .then(JSON.parse)
    .then(parseModinfos)
    .then((xs) => xs[0])

/** List of all mod IDs. */
export const allModIds = await asynciter(walk("data/mods", {
  maxDepth: 2,
  includeDirs: false,
  exts: [".json"],
  match: [/modinfo\.json/],
  skip: [/bn/],
}))
  .map(({ path }) => path)
  .concurrentUnorderedMap(extractModinfo)
  .collect()
  .then((xs) => xs.filter((x) => x !== undefined))

/**
 * see `changelog_guidelines.md` for list of all allowed scopes.
 */
export const scopes = {
  /** Default allowed scopes */
  base: ["UI", "i18n", "balance", "port", "lua"],
  /** List of `mods/<MOD_ID>` */
  mods: allModIds.toSorted().map((x) => `mods/${x}`).concat("mods"),
}

// https://github.com/Ezard/semantic-prs?tab=readme-ov-file#configuration
const config: Partial<Config> = {
  enabled: true,
  titleOnly: true,
  targetUrl: "https://docs.cataclysmbn.org/contribute/changelog_guidelines/",

  types,
  scopes: Object.values(scopes).flat(),
}

if (import.meta.main) {
  const setting = YAML.stringify(config, { quoteStyle: '"' })
  const content = outdent`
      # This file is generated by \`scripts/semantic.ts\`, do not edit manually.
      #
      # For more on configuration:
      # https://github.com/Ezard/semantic-prs?tab=readme-ov-file#configuration-options
      #
      # Validate the PR title, and ignore all commit messages
      ${setting}
    `

  const rootPath = resolve(import.meta.dirname!, "..")
  await Deno.writeTextFile(resolve(rootPath, ".github/semantic.yml"), content)
}
