LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := libmpg123

LOCAL_SRC_FILES := $(TARGET_ARCH_ABI)/libmpg123.so

LOCAL_EXPORT_C_INCLUDES += $(LOCAL_C_INCLUDES)

include $(PREBUILT_SHARED_LIBRARY)
