name: Deploy starlight documentation to GitHub Pages

on:
  push:
    branches: [main]
    paths: [doc/**]
  workflow_dispatch:


defaults:
  run:
    working-directory: doc

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04
    environment: github-pages
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload site
        uses: withastro/action@v2
        with:
          path: doc
          node-version: 20
          package-manager: pnpm@8.7.x
        env:
          CUSTOM_SITE_URL: ${{ vars.CUSTOM_SITE_URL }}
          CUSTOM_REPO_URL: ${{ vars.CUSTOM_REPO_URL }}

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
