name: JSON Validation

on:
  pull_request:
    paths: ["**.json"]

jobs:
  skip-duplicates:
    continue-on-error: true
    runs-on: ubuntu-22.04
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: "true"
          paths: '["**.json", ".github/workflows/json.yml"]'
  style-json:
    name: JSON style check

    runs-on: ubuntu-22.04
    needs: skip-duplicates
    if: ${{ needs.skip-duplicates.outputs.should_skip != 'true' }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: JSON style check
        run: deno fmt --check

      - name: Display Corrections
        if: failure()
        run: git diff
